INSERT INTO RETAIL_MOBILE_APP_CAM.COM_ST_SRVC (CD, VERSION, NM, DSCP, IS_DELETE, IS_INACTIVE, IS_SYSTEM,
                                               CREATED_BY, CREATED_DT, UPDATED_BY, UPDATED_DT, SRVC_TYP_CD)
VALUES ('SRVC_SALARY_ADVANCE', 0, 'Salary Advance Loan', 'SALARY ADVANCE LOAN', 'N', 'N', 'Y', 'SYSTEM', SYSDATE,
        'SYSTEM',
        SYSDATE, 'NON');

