spring.application.name=mbc-sdk-transfer-service
server.port=10543
server.servlet.context-path=/
project.package.controller=com.mbc.mobileapp.controller

# OracleDB connection settings
spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.37.36)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.37.37)(PORT = 1521)) (LOAD_BALANCE = yes)(failover = yes) (CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = ebank)))
spring.datasource.username=RETAIL_MOBILE_APP_CAM
spring.datasource.password=ENC(LLOikCkkmhfAiBNYF9IRIs7g3qcTCjbW)

# HikariCP settings
spring.datasource.hikari.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.37.36)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.37.37)(PORT = 1521)) (LOAD_BALANCE = yes)(failover = yes) (CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = ebank)))
spring.datasource.hikari.username=RETAIL_MOBILE_APP_CAM
spring.datasource.hikari.password=ENC(LLOikCkkmhfAiBNYF9IRIs7g3qcTCjbW)
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=2000000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=HikariBaaSApiTransfer
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.testOnBorrow=true
spring.datasource.hikari.validationQuery=SELECT 1

management.endpoints.web.exposure.include=health,prometheus
management.server.port=8699

spring.jpa.open-in-view=false

#============ KIBABA LOG ==============
kafka.kibana.brokers=10.1.37.31:9092,10.1.37.32:9092,10.1.37.33:9092
kafka.kibana.topic=app-khcn

spring.kafka.bootstrap-servers=10.1.37.31:9092,10.1.37.32:9092,10.1.37.33:9092
spring.kafka.consumer.group-id=ebanking-domestic
spring.kafka.consumer.topic=ebanking-domestic

#============ REDIS ==============
spring.redis.sentinel.nodes=redis://10.1.37.43:26379,redis://10.1.37.43:26380,redis://10.1.37.43:26381
spring.redis.slave.nodes=redis://10.1.37.43:6380,redis://10.1.37.43:6381
spring.redis.host=redis://10.1.37.43:6379
spring.redis.port=6379
spring.redis.sentinel.password=ENC(yk7//2Cnfdvq3k7+1CG5MliYb65jO1g9)
spring.redis.password=ENC(yk7//2Cnfdvq3k7+1CG5MliYb65jO1g9)
spring.redis.timeout=180000
spring.redis.mode=SINGLE
redisson.mastername=mymaster
redisson.connect.timeout=10000
redisson.timeout=3000
redisson.master.pool.size=300
redisson.slave.pool.size=300
redisson.slave.idle.size=10
redisson.master.idle.size=10

#============ ESB ==============
esb.user=ebanking_user1
esb.password=ENC(O+ejdbAgkDPKPI6bJEmGXg==)
esb.host=10.2.16.184
#esb.host=10.2.16.183
esb.request.timeout=100000
esb.connect.timeout=100000


#============ provider domestic transfer ==============
provider.domestic.transfer.fast=FAST
provider.domestic.transfer.bakong=BAKONG
provider.domestic.transfer.ciftp=CIFTP



#============ token key clock ==============
keyclock.gettoken.url=http://10.1.37.24:8833/realms/mbc-internal/protocol/openid-connect/token
keyclock.client.id=AML_MOBILE_INTEGRATE
keyclock.client.secret=ENC(3jlg8Xokiu9yXcgeFKO8y8d8hZOKcxL3/oNO5gGBCQPX9uGOPLVVNdUiuS5eHhUU)
keyclock.client.grantType=client_credentials


#============ microservice token ================================
microservice.gettoken.url=http://10.1.37.27:10462/oauth/token?grant_type=client_credentials
microservice.clent.id=mobileretail_user1
microservice.clent.secret=ENC(O+ejdbAgkDPKPI6bJEmGXg==)


microservice.host.url=http://10.1.37.27
microservice.customer.port=10463
microservice.funds.transfer.port=10465
microservice.account.port=10470
microservice.otp.share.port=10469


#================== BAKONG GW ========================================
microservice.bakonggw.host=http://10.1.37.27:8220
microservice.bakonggw.transaction.history.url=/bakong-gateway/v1.0/detail-transaction


#================== CUSTOMER =========================================
microservice.customer.host=http://10.1.37.27:10463
microservice.customer.info.url=/customer/1.0/inquiry
microservice.customer.create.url=/customer/1.0/create


#================== ACCOUNT ===========================================
microservice.account.host=http://10.1.37.27:10470
microservice.create.vipaccount.url=/beautiful-account/v1.0
microservice.create.nonsavingaccount.url=/current-account/v1.0


#============ AML SERVICE ===========================================
ms.aml.host=http://10.1.37.24:10319
ms.aml.customer.check=/mbc-aml-api/customer-screening/check


#================== FUNDS TRANSFER =====================================
microservice.funds.transfer.host=http://10.1.37.27:10465
microservice.funds.transfer.tran.url=/funds-transfer/v1.0/make
microservice.funds.transfer.revert.url=/funds-transfer/v1.0/revert
microservice.funds.transfer.bank.list.url=/funds-transfer/v1.0/%s/banks
microservice.funds.transfer.account.inquiry.url=/funds-transfer/v1.0/account-inquiry
microservice.funds.transfer.charge.transfer.url=/funds-transfer/v1.0/%s/fee/calculator
microservice.funds.transfer.limit.url=/funds-transfer/v1.0/%s/limit/calculator
microservice.funds.transfer.make.config.url=/funds-transfer/v1.0/make-transfer-config



#================== CIFTP GW ==========================================
microservice.ciftpgw.host=http://10.1.37.24:8233
microservice.ciftpgw.transaction.history.url=/ciftp-gateway/v1.0/detail-transaction


#================== HISTORY ===========================================
microservice.trans.history.host=http://10.1.37.27:10474
microservice.trans.history.url=/history-transaction/v1.0/transaction/details
microservice.trans.history.receiver.url=/history-transaction/v1.0/transaction/receiver-bakong


#================== SAVING =============================================
microservice.saving.host=http://10.1.37.27:8206
microservice.saving.create.url=/saving-account/1.0/create

#saving-fixed-deposit-endpoint
microservice.saving.fixed.deposit.get.interest.rate=/saving-account/1.0/interest-tax-rate
microservice.saving.fixed.deposit.open=/saving-account/1.0/open-deposit
microservice.saving.fixed.deposit.close=/saving-account/1.0/close-deposit
microservice.saving.fixed.deposit.topup=/saving-account/1.0/top-up


#================== OTP =================================================
microservice.otp.share.host=http://10.1.37.27:10469
microservice.get.otp.share.url=/otpshare/v1.0/getOtpShare
microservice.verify.otp.share.url=/otpshare/v1.0/verifyOtpShare


#================== IL ================================================
il.rest.url=http://10.1.37.27:10471
il.t24.version.url=/t24-query/v1.0/version
il.t24.routine.url=/t24-query/v1.0/routine



#=========== Notify via APP ========
notify.host=http://10.1.37.24:10468
notify.host.url.push-messages=/push-messages/v1.0/messages
sms.host.vn=http://10.1.27.141:8809
sms.host.vn.url.push-messages=/push-messages/v1.0/messages


#================== APIGEE ==========================================
apigee.gettoken.url=http://10.1.27.43:8888/oauth2-server/oauth/token
apigee.host.url=https://api-dev-cam.mbbank.com.vn
apigee.singalarity.uid.binding.url=/integration/mbc-ekyc/v1.0/uid-binding
apigee.singalarity.uid.binding.post.check.url=/integration/mbc-ekyc/v1.0/uid-binding-with-post-check-data
apigee.singalarity.check.ocr.ekyc.info.url=/integration/mbc-ekyc/v1.0/check-ocr-and-ekyc-info-v1

apigee.loyalty.login.url=/integration/mbc-loyalty/v1.0/login
apigee.loyalty.gettoken.url=/integration/mbc-loyalty/v1.0/getToken
apigee.loyalty.register.url=/integration/mbc-loyalty/v1.0/registerCustomer
apigee.loyalty.balance.url=/integration/mbc-loyalty/v1.0/balance
apigee.loyalty.earn.url=/integration/mbc-loyalty/v1.0/earn
apigee.loyalty.redeem.url=/integration/mbc-loyalty/v1.0/redeem

apigee.emoney.push-notify.url = /integration/mbc-emoney-notification/ePayTest/mbc-sdk-api/callbackTransactionResults

apigee.loyalty.username=admin.whychain
apigee.loyalty.password=ENC(8Rza4T1XHyRbGZ3NGJkBww==)

#============ eKYC ==============
ekyc.host=https://dev.digibank.vn:9443
ekyc.user=mbcam
ekyc.password=8coAik6eQczK6KC1L97d+wLbhEn5BI0C/4CSu+zX
ekyc.spid=MBCNO

dynkey.primary.ip=10.1.13.199
dynkey.secondary.ip=10.1.13.199
dynkey.port=19957
dynkey.userId=DynkeyDefaultUser
dynkey.tokenId=2237DF73A7
dynkey.deviceId=120163920534a6ed351ec3e5a69e9a59b870f188
dynkey.validityWnd=150


spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB

#=========== logging ============
logging.level.root=info
#logging.config=file:/deployment/config/log4j2.xml
logging.config=classpath:log4j2.xml

#hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
#hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=none
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=off

#=========== config batch size ============
spring.jpa.properties.hibernate.jdbc.batch_size = 10
spring.jpa.properties.hibernate.order_inserts = true
spring.jpa.properties.hibernate.order_updates = true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data = true

#ECM
ecm.url=http://10.1.27.43:9120/dctm-rest/repositories/ECM_CAM
ecm.username=mbc_user
ecm.password=ENC(VF0Ve7vWTs4yAkzP2HIC9S7XksdubQZk)
ecm.folder.type=dm_folder
ecm.content.file.href=enclosure

#=============== pagination.pageSize ================
pagination.pageSize=20
duration.request.limit=0
max.request.inday=1000


#=============== pagination.pageSize ================
#management.endpoints.web.exposure.include=health,prometheus
#management.server.port=8699

dynk.enabled=false

environment=dev
app.encrypt-body.enable=false

#Jasypt encrypt
jasypt.encryptor.bean=encryptorBean

register.count.refer.rm=5000
register.count.refer=10000


#config saving fixed deposit
saving.deposit.cnfg.product.code=AZ000001
saving.deposit.cnfg.category=6518
saving.deposit.cnfg.module=AZ
saving.deposit.cnfg.tax=2
saving.deposit.cnfg.interest.key=P09
saving.deposit.cnfg.month=30
saving.deposit.cnfg.year=360
saving.deposit.cnfg.percent=100
saving.msg.type=MSG_NOTI_SAVING
saving.deposit.cnfg.type=Fixed Deposit
saving.deposit.branch.code=KH0010001

#real-time-deposit-config
real.time.deposit.cnfg.product.code=AZ000002
real.time.deposit.cnfg.category=6505
real.time.deposit.cnfg.module=AZ
real.time.deposit.cnfg.tax=2
real.time.deposit.cnfg.interest.key=P10
real.time.deposit.cnfg.month=30
real.time.deposit.cnfg.year=360
real.time.deposit.cnfg.percent=100
real.time.deposit.cnfg.type=Real-time Deposit
real.time.deposit.branch.code=KH0010001


#flexi-deposit-config
flexi.deposit.cnfg.product.code=AC000001
flexi.deposit.cnfg.category=6011
flexi.deposit.cnfg.module=AC
flexi.deposit.cnfg.subproduct.code=612
flexi.deposit.cnfg.tax=2
flexi.deposit.cnfg.interest.key=2
flexi.deposit.cnfg.month=30
flexi.deposit.cnfg.year=360
flexi.deposit.cnfg.percent=100
flexi.deposit.cnfg.type=Flexi Term Deposit
flexi.deposit.branch.code=KH0010001
flexi.deposit.cnfg.maturitybackdate=60


#==========VIP temp account==========
#beau.chg.temp.acct=PL52490
beau.chg.temp.acct=USD1661000070001


#============ PUSH MESSAGE ==============
microservice.register.balance.port=10472

microservice.register.balance.notify.url=/balance-change/v1.0/notification/register
microservice.unregister.balance.notify.url=/balance-change/v1.0/notification/unregister
microservice.info.register.notify.url=/balance-change/v1.0/notification


#==========Remittance==========
microservice.remittance.port=8223
microservice.remittance.get.bank.list=/remittance-gateway/v1.0/bank-list
microservice.remittance.get.account.name=/remittance-gateway/v1.0/account-name
microservice.remittance.make-transfer-init=/remittance-gateway/v1.0/make-transfer-init
microservice.remittance.make-transfer-finish=/remittance-gateway/v1.0/make-transfer-finish
microservice.remittance.address.vn=/remittance-gateway/v1.0/vn-addresses
international.transfer.kafka.topic=REMITTANCE_TRANS_UPDATE_STATUS
msg.type.international.transfer=MSG_NOTI_REMITTANCE
remittance.promo.code=EMONEY

#==========MERCHANT======================
#microservice.merchant.host=http://10.1.37.24:8224
#microservice.merchant.get.info=/merchant-manager/v1.0/merchant-info
#microservice.merchant.create=/merchant-manager/v1.0/merchant-create

#=========MERCHANT CENTRALIZE=======
microservice.merchant.host=http://10.1.37.24:8242
microservice.merchant.get.info=/merchant-centralize/v1.0/business/merchant-info

partner.balance-change.notify.enable = false
partner.remittance-transaction.notify.enable = false
partner.balance-change.persist-unprocess.enable = false

app.encrypt.enable = false
app.encrypt.key = 0nFzLoTh6Ow4YU0V/V8g9ZuWydtr9p0sRHOlLRHyf2c=

